### ISSUE TITLE
issue with Buy now button bg colour

### ISSUE THREAD

**Issue by prateek-cedcoss** [wpswings/membership-for-woocommerce#113]
os: window11
wp: 5.8.2
wc: 5.9.0
version: 2.0.1
description: colour of buy now button in membership offer page does not change when we get mouse on it.
![image](https://user-images.githubusercontent.com/86113814/145594947-673f3c14-7903-489b-bfc4-b67bc8fd1987.png)

**Comment by rishabhmwb** [comment]
fixed

**Comment by ashish-wps** [comment]
Still Exist

https://github.com/wpswings/membership-for-woocommerce/assets/105413021/ed943b94-c001-4c60-a0a2-18f1c496a934

**Comment by navneet-cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
[scrnli_22_09_2023_11-32-24.webm](https://github.com/wpswings/membership-for-woocommerce/assets/105413021/881b2de6-51a7-469e-b986-506f062303a8)

![image](https://github.com/wpswings/membership-for-woocommerce/assets/105413021/bd41affc-1fbf-44af-b5de-49639df7c5a5)

**Comment by navneet-cedcoss** [comment]
Working fine

**Comment by ashish-wps** [comment]
Fixed
