### ISSUE TITLE
Notices on Membership Detail.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/membership-for-woocommerce#126]
**Bug Name -** Notices on Membership Detail.
**Area Path -** Front-end > My Account > Membership Details > View 
**Status -** New
**Woo Commerce Version -** 6.2.1
**WordPress Version -** 5.9
**Plugin Version -** 2.0.3
**Description -**

![image](https://user-images.githubusercontent.com/76723393/156306192-a04df5ef-f994-4b0b-85bd-e4142ce0e6a4.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
Issue not fixed.

![image](https://user-images.githubusercontent.com/76723393/157380939-a21f16e6-a65c-45e9-87c7-b4ea596a5d05.png)

**Comment by rishabhmwb** [comment]
issue resolved

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay
