### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/membership-for-woocommerce#127]
**Bug Name -** Fatal Error
**Area Path -** Back-end > Memberships > Membership Plans > Add Membership Plans > Allow Free Shipping > Manage Free Shipping
**Status -** New
**Woo Commerce Version -** 6.2.1
**WordPress Version -** 5.9
**Plugin Version -** 2.0.3
**Description -**

![image](https://user-images.githubusercontent.com/76723393/156307559-7a4f838b-dbdb-4cc6-9501-8f0efe36eb55.png)

![image](https://user-images.githubusercontent.com/76723393/156307567-bdb5e30c-4cf1-48ab-805a-950d68be8529.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
It's Not Fixed.

![image](https://user-images.githubusercontent.com/76723393/157380569-e7c9d1b9-ced1-4f61-b192-cd88810da672.png)

**Comment by rishabhmwb** [comment]
fixed
